# Generated by Django 5.2.8 on 2025-11-22 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('CASH', 'เงินสด'), ('BANK', 'บัญชีธนาคาร'), ('CREDIT', 'บัตรเครดิต'), ('LOAN', 'เงินกู้'), ('WALLET', 'E-Wallet')], max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='สำหรับบัตรเครดิต/วงเงินกู้ ถ้ามี', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('INCOME', 'รายรับ'), ('EXPENSE', 'รายจ่าย')], max_length=10)),
                ('is_debt_related', models.BooleanField(default=False, help_text='ติ๊กถ้าเป็นรายการเกี่ยวกับหนี้ เช่น ผ่อนหนี้, จ่ายบัตรเครดิต')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('IN', 'เงินเข้า'), ('OUT', 'เงินออก')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_estimate', models.BooleanField(default=False, help_text='ติ๊กถ้าเป็นรายการประเมิน/วางแผน ยังไม่ได้เกิดขึ้นจริง')),
                ('is_paid', models.BooleanField(default=True, help_text='ใช้คู่กับ is_estimate ถ้าประมาณการแล้วจ่ายจริงแล้ว')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app_finance.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_finance.category')),
            ],
        ),
    ]
