# Generated by Django 5.2.8 on 2025-11-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='งบต่อเดือนสำหรับหมวดนี้ ถ้าไม่มีให้เว้นว่าง', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='ใช้คู่กับ is_estimate ถ้าเป็นประมาณการแล้วจ่ายจริงแล้ว'),
        ),
    ]
