# Generated by Django 5.2.8 on 2025-11-24 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0002_category_monthly_budget_alter_transaction_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='งบต่อเดือนสำหรับหมวดนี้ (ถ้าไม่ตั้งงบให้เว้นว่าง)', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'เงินเข้า'), ('OUT', 'เงินออก')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('day_of_month', models.PositiveSmallIntegerField(help_text='วันที่ในเดือน (1-31) พระเอกใช้สร้างรายการของเดือนนั้น')),
                ('name', models.CharField(blank=True, help_text='คำอธิบายสั้น ๆ เช่น ค่าเช่าห้อง, ผ่อนรถ', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, help_text='เริ่มนับจากวันไหน (ถ้าไม่กรอกใช้ได้ทันที)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='สิ้นสุดวันไหน (ถ้าไม่กรอกให้ใช้ไปเรื่อย ๆ)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_finance.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_finance.category')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_recurring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='app_finance.recurringtransaction'),
        ),
    ]
