# Generated by Django 5.2.8 on 2025-11-24 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0003_alter_category_monthly_budget_recurringtransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='จำนวนเงินเป้าหมาย เช่น 100000', max_digits=12)),
                ('target_date', models.DateField(blank=True, help_text='อยากให้ถึงเป้าภายในวันไหน (ถ้าไม่กำหนดให้เว้นว่าง)', null=True)),
                ('direction', models.CharField(choices=[('IN', 'เงินเข้า'), ('OUT', 'เงินออก')], default='IN', help_text='นับยอดจากรายการแบบไหนเป็นการเดินหน้าเป้าหมาย (ส่วนใหญ่ใช้ เงินเข้า)', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='บัญชีที่เกี่ยวข้องกับเป้าหมายนี้ (ถ้ามี)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_finance.account')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='goal',
            field=models.ForeignKey(blank=True, help_text='ถ้ารายการนี้เกี่ยวข้องกับเป้าหมายเก็บเงิน ให้เลือก', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app_finance.goal'),
        ),
    ]
