# Generated by Django 5.2.8 on 2025-11-24 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0004_goal_transaction_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(help_text='1-12')),
                ('amount', models.DecimalField(decimal_places=2, help_text='จำนวนเงินงบประมาณสำหรับเดือนนั้น', max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='app_finance.category')),
            ],
            options={
                'ordering': ['-year', '-month', 'category__name'],
                'unique_together': {('category', 'year', 'month')},
            },
        ),
    ]
