# Generated by Django 5.2.8 on 2025-11-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0005_categorybudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proof_file',
            field=models.FileField(blank=True, help_text='อัปโหลดรูปใบเสร็จหรือไฟล์หลักฐาน (ถ้ามี)', null=True, upload_to='receipts/'),
        ),
    ]
