# Generated by Django 5.2.8 on 2025-11-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0006_transaction_proof_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(blank=True, help_text='ใส่สีแบบ #RRGGBB ถ้าอยากกำหนดสีเฉพาะ (ยังไม่บังคับใช้ก็ได้)', max_length=7, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
