# Generated by Django 5.2.8 on 2025-11-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0007_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='เลือก tag ได้หลายอัน เช่น เที่ยว, ครอบครัว, งาน', related_name='transactions', to='app_finance.tag'),
        ),
    ]
