# Generated by Django 5.2.8 on 2025-11-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0008_transaction_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ดอกเบี้ยต่อปี (%) เช่น 16 สำหรับ 16%', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='min_payment_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='เปอร์เซ็นต์ขั้นต่ำที่ต้องจ่ายจากยอดคงค้าง เช่น 5 สำหรับ 5%', max_digits=5, null=True),
        ),
    ]
