# Generated by Django 5.2.8 on 2025-11-25 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0009_account_interest_rate_account_min_payment_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ชื่อ template เช่น กาแฟ, BTS ไปทำงาน', max_length=100)),
                ('direction', models.CharField(choices=[('IN', 'รายรับ'), ('OUT', 'รายจ่าย')], default='OUT', max_length=3)),
                ('default_amount', models.DecimalField(blank=True, decimal_places=2, help_text='จำนวนเงินเริ่มต้น (เปลี่ยนได้ตอนบันทึก)', max_digits=12, null=True)),
                ('note', models.CharField(blank=True, help_text='โน้ตเริ่มต้น เช่น ร้านประจำ, เส้นทาง ฯลฯ', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(blank=True, help_text='บัญชีเริ่มต้น (เลือกใหม่ได้ตอนบันทึก)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_finance.account')),
                ('category', models.ForeignKey(blank=True, help_text='หมวดเริ่มต้น', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_finance.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tag เริ่มต้น เช่น เที่ยว, กาแฟ, เดินทาง', to='app_finance.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
