# Generated by Django 5.2.8 on 2025-11-26 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_finance", "0010_transactiontemplate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DebtPlanSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("NONE", "ยังไม่เลือกแผนเฉพาะ"),
                            ("SNOWBALL", "Snowball – ปิดยอดเล็กก่อน"),
                            ("AVALANCHE", "Avalanche – ดอกสูงก่อน"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="โน้ตสั้น ๆ เกี่ยวกับแผนปลดหนี้ (ถ้าอยากเขียนเพิ่ม)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DashboardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_smart_insights", models.BooleanField(default=True)),
                ("show_budget_box", models.BooleanField(default=True)),
                ("show_goals", models.BooleanField(default=True)),
                ("show_recurring", models.BooleanField(default=True)),
                ("show_today_summary", models.BooleanField(default=True)),
                ("show_trend_chart", models.BooleanField(default=True)),
                ("show_expense_pie", models.BooleanField(default=True)),
                ("show_estimate_box", models.BooleanField(default=True)),
                ("show_accounts", models.BooleanField(default=True)),
                ("show_recent_transactions", models.BooleanField(default=True)),
                ("show_debt_plan_card", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_dashboard_pref",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
