# Generated by Django 5.2.8 on 2025-12-01 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0012_alter_categorybudget_unique_together_account_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='debtplansetting',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debt_plan_setting', to=settings.AUTH_USER_MODEL),
        ),
    ]
