# Generated by Django 5.2.8 on 2025-12-01 03:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0013_debtplansetting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtplansetting',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='งบรวมสำหรับจ่ายหนี้ต่อเดือน', max_digits=12),
        ),
    ]
